### PR TITLE
Backend API to add additional cards for today

### PR DESCRIPTION
**Pull request by nickImbirev**
After this PR the user will be able to add more cards for their today's list in case they are ready to complete more within one day.

**There is breaking change in the API for today's card completing:**
- PUT endpoint became DELETE endpoint (successful status change from 200 -> 204)

### CODE REVIEW

**Comment by nickImbirev** [comment]
@imbireva please, check it out in swagger, let me know what do you think :)

**Comment by imbireva** [comment]
Sorry, but, can you explain me what exactly should I check in swagger?

I think it's good idea to allow users to choose their own cards quantity. I can implement UI for this feature. It can be input area in settings, user will be able to fill this input with their own cards number for 1 day?

**Comment by nickImbirev** [comment]
> Sorry, but, can you explain me what exactly should I check in swagger?

I think it will be useful for you to check the updates and **breaking changes** in the backend API to be aware of what's changed and how you can use it. Also, you might want to offer to change something in terms of client-server communication details (different HTTP methods or response codes, messages etc...). We can discuss the details of this interaction for sure :)

> I think it's good idea to allow users to choose their own cards quantity. I can implement UI for this feature. It can be input area in settings, user will be able to fill this input with their own cards number for 1 day?

Yeah, for sure, feel free to do that, I have only one criteria for it to be closer to the today's cards list, so it will be different from the regular card creation.

Let me know what do you think about it :)

**Comment by imbireva** [comment]
Good evening!

I ran server with an additional 'args' argument like this: 
image

**1. New feature with additional cards for today doesn't work with this mode. It's okay?**

**2. Cards for today are created out of order. It's okay?**

This is a screen video with demonstration these questions :)
https://user-images.githubusercontent.com/93445460/184701039-a81bde3e-28fc-41b8-bf38-a07691bb502e.mp4

**Comment by nickImbirev** [comment]
> New feature with additional cards for today doesn't work with this mode. It's okay?

Hmm, what do you mean by that?...

**Comment by nickImbirev** [comment]
> Cards for today are created out of order. It's okay?

Yeah, I think it is okay, because the order of the cards for today can be determined by the user, I do not think we need to sort them specifically by ourself, they all have been selected for today.. But to sort them based on their priority can be a good improvement here, I will try to implement it here.

**Comment by nickImbirev** [comment]
> Cards, added as additional for today, are deleted from list after "day's changing" in a minute? It should work this way?

Yeah, that's the correct behaviour. You do not create new cards, you only add more **already created** cards for today in case you have more time to complete them :) How does that sound?

**Comment by nickImbirev** [comment]
> I didn't catch the behavior of cards after using "Complete the specified card for today" (DELETE)

**Comment by imbireva** [comment]
> > Cards, added as additional for today, are deleted from list after "day's changing" in a minute? It should work this way?
> 
> Yeah, that's the correct behaviour. You do not create new cards, you only add more **already created** cards for today in case you have more time to complete them :) How does that sound?

Yeah, it sounds good! I just try to catch the logic, because I can't do it right away :)
So, user added additional card for today, but didn't do this task and this additional card goes back to all created cards.

**Comment by imbireva** [comment]
> > I didn't catch the behavior of cards after using "Complete the specified card for today" (DELETE)
> 
> I think the problem might be related to a sync time between the 'days'. What sync time do you have configured?

3 seconds

**Comment by imbireva** [comment]
> > New feature with additional cards for today doesn't work with this mode. It's okay?
> 
> Hmm, what do you mean by that?...
> 
> UPD: oh, yeah, I can see that on the video, I will try to replicate it locally and get back to you with the results or updates!

**I'm so sorry, it's my fault, the feature works correctly with this mode. 
Problem was with time, I run server with 3 seconds so today cards' list changed fast. I try it with time 1 minute and all is absolutely fine!**

**Comment by imbireva** [comment]
> > > I didn't catch the behavior of cards after using "Complete the specified card for today" (DELETE)
> > 
> > 
> > I think the problem might be related to a sync time between the 'days'. What sync time do you have configured?
> 
> 3 seconds

**Yeah, problem was related to a sync time between the 'days'. I'm sorry... All works correctly!**

**Review by imbireva — APPROVED** [review]
Hi, @nickImbirev! I think, everything is fine :)

**Comment by nickImbirev** [comment]
> > > New feature with additional cards for today doesn't work with this mode. It's okay?
> > 
> > 
> > Hmm, what do you mean by that?...
> > UPD: oh, yeah, I can see that on the video, I will try to replicate it locally and get back to you with the results or updates!
> 
> **I'm so sorry, it's my fault, the feature works correctly with this mode. Problem was with time, I run server with 3 seconds so today cards' list changed fast. I try it with time 1 minute and all is absolutely fine!**

Yeah, that what I was thinking, so, I added some additional logging to the whole application in a separate PR, and I will propagate the changes to this PR as well.

**Comment by nickImbirev** [comment]
So, now with the proper logging, it is visible, when and how the cards have been updated, I checked the behaviour and it is correct! I hope I answered all the questions about the business logic so far :)

**Pull request merged**
