### PR TITLE
Add an ability to change today's card priority based on the user input

### PR DESCRIPTION
**Pull request by nickImbirev**
After this PR the user will be able to change the order of their's today cards in case they want to reorder them for the simplicity.

There is an additional change introduced:

- A new configuration limitation for the number of today's cards has been set up to 100 to avoid performance issues.

### CODE REVIEW

**Comment by imbireva** [comment]
Hello, @nickImbirev :)

Thank you, I checked this new feature. 
To use it I should give the algorithm, which will be used to do something with today cards array, right?

> A new configuration limitation for the number of today's cards has been set up to 100 to avoid performance issues

got it!

**Comment by nickImbirev** [comment]
> To use it I should give the algorithm, which will be used to do something with today cards array, right?

Hmm, yeah, you can define any suitable algorithm on the client side in order to satisfy the user needs, this backend API can be used to store the applied cards order, but not the algorithm itself.. So, I would propose to implement something like drag and drop feature to allow the user to define their our custom cards order and save it between the user sessions. Hope that helps!

**Comment by imbireva** [comment]
@nickImbirev, sorry, but now I don't understand how it should work...

I have this error after trying it out:
image

Also assign-today-cards-priority branch doesn't have my clients folder, so locally I have a lot of untracked files (node modules etc). But maybe it doesn't matter because I'm not gonna work on this branch.

What do you think about it? 
Maybe we can discuss it on online-meeting?

**Comment by nickImbirev** [comment]
>  assign-today-cards-priority branch doesn't have my clients folder

Yeah, I understand the problem, I just merged it with master, so, it should work properly.

**Comment by nickImbirev** [comment]
UPD: I see, you notices a bug that I have in the Swagger declaration for the new endpoint, thank you for this! I fixed it in the latest commit, please, check it out :)

**Comment by imbireva** [comment]
> > assign-today-cards-priority branch doesn't have my clients folder
> 
> Yeah, I understand the problem, I just merged it with master, so, it should work properly.

Yes, now it's fine! Thank you

**Comment by imbireva** [comment]
> UPD: I see, you notices a bug that I have in the Swagger declaration for the new endpoint, thank you for this! I fixed it in the latest commit, please, check it out :)

Yeah, now it's okay, I have an ability to fill request body and see how today cards list changes.

**Comment by imbireva** [comment]
> So, I would propose to implement something like drag and drop feature to allow the user to define their our custom cards order and save it between the user sessions. Hope that helps!

It would be great! ( I have never done drag and drop, but I would like to try :) )

**Review by imbireva — APPROVED** [review]
I approve these changes :)

**Pull request merged**
