### PR TITLE
Add simple Github CI pipeline for the Browser client

### PR DESCRIPTION
**Pull request by nickImbirev**

### CODE REVIEW

**Comment by nickImbirev** [comment]
You can check the results now :)

**Comment by imbireva** [comment]
> You can check the results now :)

Hi :) I didn't catch, what is it and how I can use it...

**Review by imbireva — APPROVED** [review]

**Comment by nickImbirev** [comment]
> I didn't catch, what is it and how I can use it...

Now, after these changes, you can check the statuses of the PRs in this [tab](https://github.com/nickImbirev/cards-service/actions), additionally, you always will be able to find, whether the changes pass the Continuous Integration pipeline or not by checking this checkmark or red cross in the PR title:

Screenshot 2022-09-11 at 17 20 55

**Comment by nickImbirev** [comment]
For now, the pipeline contains only three simple steps:

1. Install dependencies (to check, whether we have any issues with the dependencies or not)
2. Lint (to check, whether the changes can be compiled and follow the same code style format)
3. Build (to check, whether the changes can be built together without any errors)

**Pull request merged**
